version: 2

jobs:
  build:
    docker:
      - image: kapost/ruby:2.3.1-node-6.11.5
        environment:
          DATABASE_URL: "postgres://circleci@localhost/clone_kit_test"
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: clone_kit_test
      - image: kapost/mongo:3.0

    working_directory: ~/clone_kit

    steps:
      - checkout

      - restore_cache:
          keys:
            - bundle-v1-{{ arch }}-{{ .Branch }}-{{ checksum "clone_kit.gemspec" }}
            - bundle-v1-{{ arch }}-{{ .Branch }}
            - bundle-v1-{{ arch }}
      - run:
          name: Bundle Install
          command: |
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: bundle-v1-{{ arch }}-{{ .Branch }}-{{ checksum "clone_kit.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Specs
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results
